# Generated by Django 4.0.1 on 2022-01-10 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_task_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
