# Generated by Django 4.0.1 on 2022-01-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_task_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='uid',
        ),
        migrations.AddField(
            model_name='task',
            name='order_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
