# Generated by Django 4.0.1 on 2022-01-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('icon', models.ImageField(null=True, upload_to='icons/', verbose_name='Иконка')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='statuses',
            field=models.ManyToManyField(blank=True, to='data.ProjectStatus'),
        ),
    ]
