# Generated by Django 4.0.1 on 2022-01-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_projectstatus_project_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет, например red, blue, green'),
        ),
    ]
